package br.com.tc.view;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.declarative.Design;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.Button;

/**
 * !! DO NOT EDIT THIS FILE !!
 * <p>
 * This class is generated by Vaadin Designer and will be overwritten.
 * <p>
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public abstract class ConfirmationView extends VerticalLayout {
	protected Label l_message;
	protected Button yes;
	protected Button yes_d;
	protected Button no;
	
	/**
	 * @author Jeronimo
	 * @since 04/06/2017
	 */
	public ConfirmationView() {
		Design.read(this);
	}
}
