package br.com.tc.view;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.declarative.Design;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Button;
import com.vaadin.ui.CssLayout;
import com.vaadin.ui.Label;

/**
 * @author Jeronimo
 * @since 25/05/2017
 * !! DO NOT EDIT THIS FILE !!
 * <p>
 * This class is generated by Vaadin Designer and will be overwritten.
 * <p>
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public abstract class MenuView extends HorizontalLayout {
	protected Button menuButton;
	protected CssLayout menu;
	protected Button cliente;
	protected Button contrato;
	protected Button financeira;
	protected Button caixa;
	protected Button relatorio;
	protected Button admin;
	protected Label view_title;
	protected CssLayout content1;
	protected CssLayout content2;
	protected CssLayout content3;
	
	/**
	 * @author Jeronimo
	 * @since 25/05/2017
	 */
	public MenuView() {
		Design.read(this);
	}
}
