package br.com.tc.view;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.declarative.Design;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.TextField;
import com.vaadin.ui.Button;
import com.vaadin.ui.Grid;
import com.vaadin.ui.PasswordField;
import com.vaadin.ui.CheckBox;
import com.vaadin.ui.Label;

/**
 * @author Jeronimo
 * @since 28/05/2017
 * !! DO NOT EDIT THIS FILE !!
 * <p>
 * This class is generated by Vaadin Designer and will be overwritten.
 * <p>
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
abstract public class UsuarioGridView extends VerticalLayout {
	protected TextField search;
	protected Button add;
	protected Grid<br.com.tc.model.Usuario> list;
	protected Label action_title;
	protected TextField nome_usuario;
	protected PasswordField senha;
	protected CheckBox cliente_visualizar;
	protected CheckBox cliente_gravar;
	protected CheckBox cliente_excluir;
	protected CheckBox contrato_visualizar;
	protected CheckBox contrato_gravar;
	protected CheckBox contrato_excluir;
	protected CheckBox financeira_visualizar;
	protected CheckBox financeira_gravar;
	protected CheckBox financeira_excluir;
	protected CheckBox caixa_visualizar;
	protected CheckBox caixa_gravar;
	protected CheckBox caixa_excluir;
	protected CheckBox relatorio;
	protected CheckBox comissao;
	protected Button save;
	protected Button delete;
	
	/**
	 * @author Jeronimo
	 * @since 28/05/2017
	 */
	public UsuarioGridView() {
		Design.read(this);
	}
}
